### PR TITLE
fix: add attributes to IUserProfileResponse

### LINKED ISSUE #3: IUserProfileResponse missing attributes
Interface is only containing:
- last_name
- first_name

Example response body from API:  

```json
{  
  "first_name": "Eivind",  
  "last_name": "Dalholt",  
  "email": "eivind@dalholt.no",  
  "phone_number": "+47123456789",  
  "gender": "M",  
  "date_of_birth": "2069-06-09",  
  "address": "Some street",  
  "zip_code": "4242",  
  "ntnui_no": 123456,  
  "register_date": "2020-08-08",  
  "contracts": [  
    {  
      "expiry_date": "2023-08-31",  
      "type": "student_membership"  
    },  
    {  
      "expiry_date": "2022-08-31",  
      "type": "student_membership"  
    },  
    {  
      "expiry_date": "2021-08-10",  
      "type": "student_membership"  
    }  
  ],  
  "contract_expiry_date": "2023-08-31",  
  "access_id": "",  
  "bank_account_number": "",  
  "memberships": [  
    {  
      "group": "Tindegruppa",  
      "slug": "tindegruppa",  
      "membership_no": 1234,  
      "type": "member",  
      "group_expiry": "2023-12-31",  
      "subgroups": []  
    },  
    {  
      "group": "Sprint",  
      "slug": "sprint",  
      "membership_no": 2345,  
      "type": "board_member",  
      "group_expiry": "2023-12-31",  
      "subgroups": []  
    },  
    {  
      "group": "Seiling",  
      "slug": "seiling",  
      "membership_no": 3456,  
      "type": "board_member",  
      "group_expiry": "2023-12-31",  
      "subgroups": []  
    }  
  ],  
  "sit_email": "mail@stud.ntnu.no",  
  "contact_email": "eivind.dalholt@ntnui.no"  
}

### PR DESCRIPTION
**Pull request by edalholt**
Closes #3 

Added to IUserProfileResponse:
from https://api.ntnui.no/users/profile/
```json
date_of_birth?: string,
address?: string,
zip_code?: string,
register_date?: string,
email: string,
sit_email?: string,
contact_email?: string,
phone_number: string,
ntnui_no: number,
contract_expiry_date?: string,
memberships: {
	group: string,
	slug: string,
	membership_no: number,
	type: string,
	group_expiry: string
}[]

### CODE REVIEW

**Review by eivindkopperud — APPROVED** [review]
Haven't tested locally, but the code seems fine. Might be enhanced by adding a I membership such that `memberships` can be declared as IMembership[]. Good job taking initiative on this one!

(@LiviaValenti or @Xtrah should probably give an approval here as well, since they know it the best)

**Comment by edalholt** [comment]
Will this fix be released soon?
This is practical for our bachelor project:)
@Xtrah @LiviaValenti

**Comment by eivindkopperud** [comment]
Merge it and we'll bump the minor version soon. If it doesn't work we will add a patch version

**Comment by edalholt** [comment]
Great! I had to use --transpile-only in vote until the new version 📉

**Pull request merged**
